import AuthProvider from "./components/AuthProvider/AuthProvider";
import Minicart from "./components/Cart/Minicart";
import Header from "./components/UI/Header";
import CartProvider from "./context/CartProvider";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <CartProvider>
            <Header />
            <Minicart />
            <main className="mx-auto px-6 xl:max-w-7xl">{children}</main>
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
